-- https://school.programmers.co.kr/learn/courses/30/lessons/131535

-- Oracle
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
AND AGE BETWEEN 20 AND 29;

-- MySQL
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE AGE >= 20 AND AGE <= 29
AND DATE_FORMAT(JOINED, '%Y') = '2021';