-- https://school.programmers.co.kr/learn/courses/30/lessons/59412

-- Oracle	SUBSTR 사용 시, 9가 09로 처리되어 오답처리
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS "HOUR", COUNT(*) AS "COUNT"
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN '09' AND '19'
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY HOUR;

-- MySQL
SELECT SUBSTR(DATE_FORMAT(DATETIME, '%H'), 1, 2) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H:%i') BETWEEN '09:00' AND '19:59'
GROUP BY HOUR
ORDER BY HOUR;