-- https://school.programmers.co.kr/learn/courses/30/lessons/131529

-- Oracle
SELECT SUBSTR(PRODUCT_CODE,0,2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE,0,2)
ORDER BY CATEGORY;

-- MySQL
SELECT SUBSTR(PRODUCT_CODE,1,2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;