-- https://school.programmers.co.kr/learn/courses/30/lessons/59047

-- Oracle
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog'
AND LOWER(NAME) LIKE '%el%'
ORDER BY NAME;

-- MySQL
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'dog'
AND NAME LIKE '%el%'
ORDER BY NAME;